### PR TITLE
Implicit baseline + plugins update

### PR DESCRIPTION
**Pull request by tiborauer**
This PR allows using implicit baseline, which simplifies the protocol files and reduces the design matrix for iGLM thus, hopefully, improving its stability. It also fixes some confusing hardcoding regarding regressor selection for signal cGLM. Now, the order of (selected) regressors are specified in `P.CondNames` as defined in _loadProtocolData.m_. 
The bundled protocol files have also been modified accordingly. The protocol file for the DCM has been left untouched.

Further updates are related to plugins:
- allows plugins running at t4
- allows post-initialization of plugins
- allows plugin codes (also matlab) in one plugins folder
- allows plugin finalization before destruction

Further debugs:
- omitting (accidental, I guess) variable printout during setup
- ContTask ini file
- plugin finalization often does not run
- plugins ROI iGLM fails with single ROI

### CODE REVIEW

**Comment by ykoush** [comment]
Thank you, looks good, please let me know what stops you from finishing DCM type to the same format.
Ideally, we have to keep the things homogeneous.

**Comment by tiborauer** [comment]
@ykoush, I am not familiar with the DCM implementation, and I have noticed that the DCM protocol has several consecutive BAS blocks, which would be modelled together in case of an implicit baseline.
There is also the SVM type, which uses the BAS for classification. One option would be to use the NFBREG with -1 contrast, however, the two are computationally not equivalent.

**Comment by TheAmid** [comment]
I have checked this PR on PSC_cont, DCM and REST data, and I got the following error on SVM data

Traceback (most recent call last):
  File "C:\OpenNFT\opennft\opennft.py", line 778, in callMainLoopIteration
    self.updatePlugins()
  File "C:\OpenNFT\opennft\opennft.py", line 493, in updatePlugins
    for i in range(len(self.plugins)): self.plugins[i].update()
  File "C:\OpenNFT\opennft\plugin.py", line 48, in update
    exec("self.object." + m['plugin_exec'])
  File "<string>", line 1, in <module>
AttributeError: 'float' object has no attribute '_data'

Is it related to this PR or we missed it earlier?

**Comment by tiborauer** [comment]
@TheAmid, this error is not related to this PR, but I have added the debug to this one. It also requires the updated version of pyniexp (>=0.21.3).

**Comment by TheAmid** [comment]
I updated everything and checked again. It works perfectly with SVM.

But I have some concern about plugins. I tested a performance with and without them. As it was written in "statmap" plugin, it slows down OpenNFT significantly. Approximately:
DCM - 0.1 sec
PSC_cont - 0.15 sec
TASK - 0.3-0.5 sec
And REST.... I got processing time aroung 2.8 seconds before iGLM and 4.4 seconds after it. Also, I had 100% CPU usage (i7-8700)

**Comment by ykoush** [comment]
Right, @TheAmid keeps commenting to this one, yet this is not relevant PR, instead, I made an issue #73 to continue on it.
Btw, I think @TheAmid forgot to mention that without plugins TASK and REST modes have <1.4 sec in total. 
TASK and REST Demo data are good examples of high volume data, acquired for non-real-time fMRI, i.e. good to test timing issues on new approaches.

**Comment by tiborauer** [comment]
I have responded in #73.

**Comment by tiborauer** [comment]
I have updated the PR based on #74

**Pull request merged**
