### PR TITLE
Connectivity

### PR DESCRIPTION
**Pull request by tiborauer**
NEW - This PR adds feedback calculation based on the correlation between two ROIs. 
- Use case with more than two ROIs is not supported!
- The feedback is computed based on scaled time-series values adjusted for HRF delay during the condition block and presented in an intermittent way (i.e. as a single value at the end of the condition block).
- Negative feedback values are cut in the current configuration, but it can be enabled similarly to the other feedback types.

ENH - flagType is simplified and refactored to allow further extension
ENH - optional plotting of the feedback value is implemented and can be enabled in config.py (line 60: PLOT_DISPLAYVALUE). If enabled, an additional line plot is added to the bottom plot. 

FIX - sending conditions via UDP

### CODE REVIEW

**Comment by tiborauer** [comment]
Hi @TheAmid, Thanks. It should have failed previously, as well. Anyway, I committed a fix.

**Comment by TheAmid** [comment]
Works perfectly!

**Comment by TheAmid** [comment]
It would be great to show the corr values during intermittent blocks as an extra plot on norm-plot panel, because the values are [0..1]

Please describe the mecahnism how exactly the feedback was computed in caption, e.g. based on which data and in which feedback type.

Seemingly, the feedback was computed based on values of the condition blocks only, how this approach was validated, and why baseline points are not included?

**Comment by tiborauer** [comment]
Thanks for the suggestions, @TheAmid, however, I am not sure what and how to plot, because the feedback is a single value for the whole period included; so for the example dataset of 155 volumes with 7 regulation blocks, there would be 7 dots.

The feedback was computed based on PSC values during the condition block, and I do not think it makes sense to compute it based on any other feedback type. That is why I have not discussed it.

Baseline points are not included because the participant would attempt to improve the correlation only during the condition block; therefore, it does not make sense to include the baseline points. Moreover, including the baseline points would confound the correlation, because the signal change between the baseline and the condition is likely to be larger (and due to a different reason) than within the condition block. It would be hard to disentangle the signal change due to the process of the regulation and the signal change due to the effectiveness of the regulation (i.e. improved functional connectivity).
The approach is similar to what has been proposed in https://doi.org/10.1371/journal.pone.0085929 ("full task window").

**Comment by ykoush** [comment]
Practically, it is possible to show these few identical dots during the intermittent blue blocks - they will be visible, i.e. creating the extra variable within normalized values. I agree that it is somewhat not intuitive to plot, but during real-time, if the 2nd monitor is only subjects' monitor, an operator has now idea what the value subject is seeing, and if the things are working as intended during the session. 
The description of added feedback (In caption of the PR) is missing the notion that it is intermittent and based on condition PSC only. It would be very helpful to get them, because practically, one could do many other options of getting corr, including continuous, and just sliding-window-based with baseline points as well.
I completely understand the discussion about baseline bias and PSC bias. But the current corr feedback is based on scaled time-series, and if I remember well, the scaling is done on cumulative baseline estimates. The PSC is also based on cumulative baseline estimates. So I think, here you don't mean the PSC signal, but just scaled time-series. So there is some intrinsic baseline bias anyway in the present approach.

**Comment by tiborauer** [comment]
- I take a look at the intermittent PSC design to see how the visualisation can be implemented. 
- I have updated the PR caption.
- It is true that there is a baseline bias in the block-by-block variation but not in the within-block variation, which is more important for correlation. If I would include the baseline then the variation between the baseline and the condition would likely dominate over the within-block variation.

**Comment by tiborauer** [comment]
- I would also consider the visualization useful, however, I am not sure how much work it would be and how much it would change the existing plotting. My current approach is to leave that burned to the visualization program, which can display them to the operator if needed.

**Comment by tiborauer** [comment]
I have added plotting fb value

**Comment by ykoush** [comment]
Great! but I don't understand why you are saying: 'The feedback is computed based on PSC values', If I'm not mistaken by just a quick look, to me it looks rather as 'based on scaled time-series values'.

**Comment by tiborauer** [comment]
You are right! I said PSC bacuase I thought I should point to a feedback type.

**Comment by ykoush** [comment]
We identified a few minor issues: 1) the json used for corr needs to be INT instead of CONT. 2) Please add in comments above that time-series values taken for corr() are adjusted for HRF delay, i.e i_blockNF is shorter than the real block, and 3) than negative values are cut.
Also @TheAmid we can add a plot here

**Comment by TheAmid** [comment]
It seems there is something wrong with new plot drawing. Initially, I setup and run PSC_conn. After it finished I tried to run PSC_int I found that:

Traceback (most recent call last):
  File "C:\OpenNFT\opennft\opennft.py", line 964, in callMainLoopIteration
    self.drawRoiPlots(init)
  File "C:\OpenNFT\opennft\opennft.py", line 2233, in drawRoiPlots
    dataNorm = np.concatenate((dataNorm,np.array([self.displaySamples])/self.P['MaxFeedbackVal']))
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 153

I guess it might be a problem with initialization of self.displaySamples. I moved it to setup function and it fixed the problem.

**Comment by tiborauer** [comment]
@TheAmid, Do you want to submit a PR to my branch?

**Comment by ykoush** [comment]
We mean it should be easier for you, no need for an extra PR over PR.

**Comment by tiborauer** [comment]
I have added the suggested changes. Two comments:
- The JSON used for `conn `is neither `int` or `cont `but a dedicated JSON `conn`. It was based on `cont`, indeed, so I have changed it so that it mimics `int`
- I have also noticed that no FB value is sent during NFBDISP condition. Is it intentional also assuming that the visualization program shows the value sent last?

**Comment by TheAmid** [comment]
It's seems something wrong with other datasets, specifically with DCM (after first trial) and REST (at the begining). 

I assume that correlation plot shouldn't be available during these two datasets and additional condition in the line 2232 in opennft.py may fix it.

```
Traceback (most recent call last):
  File "C:\OpenNFT\opennft\opennft.py", line 963, in callMainLoopIteration
    self.drawRoiPlots(init)
  File "C:\OpenNFT\opennft\opennft.py", line 2233, in drawRoiPlots
    dataNorm = np.concatenate((dataNorm,np.array([self.displaySamples])/self.P['MaxFeedbackVal']))
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 0
```

**Comment by tiborauer** [comment]
I think the reason is the PLOT_DISPLAYVALUE=true. For DCM and REST there is no value to display/plot and/or it does not correspond with the rest of the plots.
One solution is to put config.PLOT_DISPLAYVALUE into the ini files, so that each use case can have different settings.

**Comment by ykoush** [comment]
Agree, just please do this transition.

**Comment by tiborauer** [comment]
Done!

**Pull request merged**
