### PR TITLE
ContTask NFB protocol implemented on top of latest release

### PR DESCRIPTION
**Pull request by lucp88**
Same changes as first PR. Only added change is in setupBasicPlots to correct for the last block not being shown on the panel plots in the GUI. Its not taking care of the real 'issue'  however (only corrected for my condition). The real ''issue'' is in createMusterInfo. As commented by one of you, it needs to be optimized so that i can take any protocol.

### CODE REVIEW

**Comment by espdev** [comment]
> The real ''issue'' is in createMusterInfo. As commented by one of you, it needs to be optimized so that i can take any protocol.

Yes. This is my comment. We need to rewrite this function and make it universal for creating plots for any protocols.

**Comment by ykoush** [comment]
I extended and clarified on suggested time stamps: ( [9fc5893]( https://github.com/OpenNFT/OpenNFT/commit/c161c701c2a992848d5ec666bf8026900ce458af)).

Please keep in mind the entire time-flow specified in the ms, both # t2 and # t6 are related to data acquisition and post processing steps of the already acquired volume. It is possible to use these times in post-processing given their meaning.

**Comment by ykoush** [comment]
And, I guess this is an intended 2 sec delay before you start the task:

**Comment by lucp88** [comment]
> And, I guess this is an intended 2 sec delay before you start the task:
> [OpenNFT/opennft/matlab/nfbDispl/ptbTask.m](https://github.com/OpenNFT/OpenNFT/blob/16527a45ab3d756d7b059b7bb2d18a2947f5702e/opennft/matlab/nfbDispl/ptbTask.m#L27)
> 
> Line 27 in [16527a4](/OpenNFT/OpenNFT/commit/16527a45ab3d756d7b059b7bb2d18a2947f5702e)
> 
>  WaitSecs(2)

yes just randomly set to 2 seconds here as an example

**Comment by lucp88** [comment]
> I extended and clarified on suggested time stamps: ( [9fc5893](https://github.com/OpenNFT/OpenNFT/commit/c161c701c2a992848d5ec666bf8026900ce458af)).
> 
> Please keep in mind the entire time-flow specified in the ms, both # t2 and # t6 are related to data acquisition and post processing steps of the already acquired volume. It is possible to use these times in post-processing given their meaning.

ah i see, thanks for the clarification.. I wasn't sure :)

**Pull request merged**
