### PR TITLE
FIX - plugins after recent updates

### PR DESCRIPTION
**Pull request by tiborauer**
This PR updates plugins by adapting recent changes.

### CODE REVIEW

**Comment by tiborauer** [comment]
Strange! It works for me without any issue. I wonder where "Whole brain" comes from. It seems your `P.ROINames` contains it for some reason... For me
``` matlab
>> P.ROINames

ans =

  2×1 cell array

    {'C:\_RT\rtData\NF_PSC\ROIs_D1\lROI_1.nii'}
    {'C:\_RT\rtData\NF_PSC\ROIs_D1\rROI_2.nii'}
```

**Comment by TheAmid** [comment]
It seems you disabled rtQA, because "Whole brain" ROI is a part of rtQA. Without rtQA it works ok.

**Comment by ykoush** [comment]
@tiborauer there should be no error conflicting the whole-brain ROI functionality, i.e. with rtQA on. This ROI is automatically generated and added at the end of the list of ROIs if rtQA is on, and this is the only ROI in the auto rtQA mode.

**Comment by tiborauer** [comment]
I do not think the concept is the issue but the implementation because `P.ROINames` contains a description (i.e. "Whole brain") rather than path to a volume.

**Comment by tiborauer** [comment]
I have updated the plugin so it takes the pre-loaded ROIs. It passes also with rtQA.

**Comment by TheAmid** [comment]
Something wrong with the second plugin (ROI step-wise GLM)

On PSC_cont data, when I stopped the run:

```
Process Process-17:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\OpenNFT\OpenNFT_venv_397\lib\site-packages\pyniexp\mlplugins.py", line 62, in _run
    self.finalize_process()
  File "C:\OpenNFT\opennft\plugins\onp_roiswglm.py", line 78, in finalize_process
    ax = plt.subplot(120+(r+1), projection='3d')
  File "C:\OpenNFT\OpenNFT_venv_397\lib\site-packages\matplotlib\pyplot.py", line 1272, in subplot
    key = SubplotSpec._from_subplot_args(fig, args)
  File "C:\OpenNFT\OpenNFT_venv_397\lib\site-packages\matplotlib\gridspec.py", line 663, in _from_subplot_args
    return gs[i-1:j]
  File "C:\OpenNFT\OpenNFT_venv_397\lib\site-packages\matplotlib\gridspec.py", line 260, in __getitem__
    num1, num2 = _normalize(key, nrows * ncols, None)
  File "C:\OpenNFT\OpenNFT_venv_397\lib\site-packages\matplotlib\gridspec.py", line 237, in _normalize
    raise IndexError("GridSpec slice would result in no space "
IndexError: GridSpec slice would result in no space allocated for subplot
```

And, I supposed, it would be more user-friendly to disable ROI step-wise GLM plugin for non-continuous.
Other plugins work great on PSC_cont, PSC_int and SVM demo data.

**Comment by tiborauer** [comment]
I have added a plugin-protocol compatibility check.

**Comment by tiborauer** [comment]
I have found and fixed the error. I also updated the data transfer for the plugins.

**Pull request merged**
