### PR TITLE
protocols, model helper, and roi-swglm

### PR DESCRIPTION
**Pull request by tiborauer**
- This PR updates protocols and their handling to resolve bugs related to SVM and DCM after removing Baseline definitions.
- It also resolves some ambiguity on model helpers (i.e. either PTB_HELPER or MATLAB_MODEL_HELPER is required for DCM)
- It introduces a new plugin implementing step-wise GLM for ROIs.

### CODE REVIEW

**Comment by TheAmid** [comment]
Checked. Works perfectly, but I have one error when running REST data

Traceback (most recent call last):
  File "C:\OpenNFT\opennft\opennft.py", line 1293, in setup
    for i in range(len(self.plugins)): self.plugins[i].initialize()
  File "C:\OpenNFT\opennft\plugin.py", line 48, in initialize
    self.object = eval("self.module." + initcmd.format(**self.parent.P))
KeyError: 'ProtNF'

**Comment by tiborauer** [comment]
You seem to use the onp_roiswglm plugin, which requires a Protocol the REST data do not have. I consider such a use case an inappropriate one.

**Comment by TheAmid** [comment]
Could you please add the exception then so that plugin is not executed in REST?

**Comment by tiborauer** [comment]
I would rather add a more transparent solution, which prevents selecting unsuitable plugins. But that would take a bit more time.

**Comment by ykoush** [comment]
I agree. If it doesn't take long I'd  just add a quick solution for now, so that we could quickly merge preventing possible errors for REST mode. Otherwise, may be just add a comment in plugin description.

**Comment by tiborauer** [comment]
I have added exception handling. Also, the erroneous plugin is removed from the analysis.

**Pull request merged**
