### PR TITLE
Modifications necessary to read dcm definition from protocol file

### PR DESCRIPTION
**Pull request by moritz-gruber**
Hi all!
 
I incorporated the DCM definition process into the protocol JSON file, as we (SNS lab) are internally trying to minimize the number of experiment-specific files/scripts one needs to modify for each experiment. Here, 

* I incorporated the DCM definition into the protocol JSON file by adding a new key: `dcmdef`. This includes target and opposed model topology, options and ROI names. 
* created `parseDCMdef.m`, a function that extracts the DCM definition from the JSON file and returns the DCM fields
* Adapted `dcmPrep.m` to read from the protocol file and set the DCM definitions accordingly
* Adapted `dcmBegin.m` to dynamically depend on dcmPrep (no longer requiring manual modification)
* Made a minor change to `loadProtocolData.m` to remove the newly introduced JSON field from the `P` struct so as not to cause data type errors in python

In my tests, this version yielded the exact same feedback values as the default implementation. 

Perhaps this is something you might be interested in incorporating.

### CODE REVIEW

**Comment by tiborauer** [comment]
Sounds like a great idea! Have you also tested the other examples, too, to ensure you did not break anything there?

**Comment by moritz-gruber** [comment]
The only file relevant to other types of feedback was `loadProtocolData.m`, and my initial modification would have indeed broken non-DCM feedback experiments. Thanks for pointing that out—I just fixed it. Aside from that, I can't come up with a scenario where my modifications could affect other experiments. 
Did you have any specific concerns?

**Comment by tiborauer** [comment]
Have you tested on all examples?

**Comment by moritz-gruber** [comment]
May I ask what you exactly mean by "other examples"? Are you referring to other types of feedback (no) or different DCMs (yes)?

**Comment by tiborauer** [comment]
I mean the examples/demos provided with/for OpenNFT: https://github.com/OpenNFT/OpenNFT#demo-dataset

**Comment by ykoush** [comment]
Hi here, 
thank you Mortiz for a very nice extension of DCM setup! I'll have time to check it on my PC a bit later, but you are right that there are no other examples that fit much the DCM changes, since DCM is quite isolated from many other parts of code. However, e.g. if you introduce a new filed in .ini file, we copy it across other feedback types, which makes ini files uniform across other feedback types. If the new parameter has nothing to do with other feedback types, it just shouldn't appear in ini file, but rather in config.py file. This is based on our experience.
So, from this perspective, e.g. a field 'dcmdef' should be either added to all ini files in configs (seems unnecessary) or moved to config.py. Other changes seem to be all DCM-specific.

**Comment by moritz-gruber** [comment]
Hi Yury, thanks for your response.

I did not change the `.ini` files, so unless there is some cross-talk between `JSON` and `.ini` files (that I may well be unaware of), I am not sure I understand your concerns. Could you elaborate on what you mean by "we copy it across other feedback types"?

Also, would you rather store the DCM topologies and options within `config.py` instead of the JSON protocol file? This might make things slightly easier to pass to MATLAB but add one more (strictly) experiment-specific file that the end user needs to be aware and keep track of.

**Comment by ykoush** [comment]
I think I also misunderstood wrt  'dcmdef' thinking it was in ini. But to answer your question, 'copying' means extending any of/all configs to hold the genearlity, i.e. if the 'contrast' term is introduced in one of the .json, it has to be created in all the other .jsons, as well as the code logics is to be modified accordingly. This makes the PR complete, e.g. the current PR #33 is to be completed. So I probably messed between #33 and #34, but the concern is indeed true. We have to keep the thumb rule to let all PRs to be as general as possible for the entire soft, especially if the concept concerns changing the .json or .ini. 
In principle we could keep some more feedback-specific sets in .json, but initially, it was suggested to be only the Protocol, which keeps them all of the same file structure. Extending DCM .json for feedback type settings/model settings, kind of changes this general concept, but at the same time, it appears convenient. 
However, trick solutions could not be avoided to handle current python error as you write, I'm wondering what the error do you get. May be it could be possible to fix it in python instead of removing the prt filed? I mean it would be quite some fun if all the extra fields will be handled this way after a while.

**Comment by moritz-gruber** [comment]
I understand your concern: having a series of rmfields is bound to become ugly and confusing. How about this:
We could replace the somewhat hacky `rmfield` by a `prt-cleanup`-function (small enough to fit at the bottom of `loadProtocolData.m`) that simply discards all feedback-type specific fields. This avoids major changes in logic while keeping the code clean and flexible. 

The problem in python is that nested lists in JSON are returned as MATLAB cell arrays by `loadjson`, which python does not know how to handle, hence throwing a `TypeError` (unsupported data type) when self.P is updated on line 1106 after the call to `loadProtocolData`:

```python
self.P.update(self.eng.workspace['P'])
```

I don't see an easy way of handling this strictly within python. Would you agree that the slight (and benign) modification I propose to `loadProtocolData` is worth the convenience gained by no longer having to touch any of the DCM MATLAB functions?

**Pull request merged**
