### PR TITLE
ContTask NFB protocol 

### PR DESCRIPTION
**Pull request by lucp88**
Hi, 

I added a continuous task (ConTask) NFB protocol. Example stims can be found in the TaskStims folder. It's a bit large so it's zipped. On my pc everything checks out and is working smoothly. Still need to implement the event recordings of the task onset. 

Cheers!

Lucas

### CODE REVIEW

**Comment by tiborauer** [comment]
Upon quickly skimming through the code, I am wondering whether it should be further optimised:
- Stimulus: 
  - The compression does not reduce the size of the .mat file.
  - Sm10.bmp is added both as a file and as part of the zip.
  - The .zip file has an empty folder "1".
  - The five cells in all_images seem to be identical. 
  - .mat files are not really transparent, modular and/portable. Sharing the images would allow more flexibility, because users can replace the files with their own ones.
  - .bmp is not an economic format. I recommend .png.
- Organisation:
  - Stimulus heavily increase the size of the repo and it is useful only for a special use case. I recommend to publish separately similarly to the example dataset.
  - Adding a setting, e.g. TaskFolder, would further allow configurability and separability from the main codebase.
  - We should keep `P` variable as light as possible to avoid long loading between iterations. Stimuli should be loaded into a separate `Tex` variable, because they are used only within MATLAB.

**Comment by lucp88** [comment]
2 questions:

1) _"Adding a setting, e.g. TaskFolder, would further allow configurability and separability from the main 
 codebase"_ I'm not exactly sure what you mean by this, should I add a TaskFolder directory entry in the GUI that links to the folder containing the stimuli/images?

2) About the seperate tex structure that stays in matlab, this would also apply for the inter and interblock conditions? Alternativley I could reduce the images used in the task example to 10 per taskblock (instead of 150).

**Comment by tiborauer** [comment]
Ad 1.: Yes. I suggest corresponding entries in the GUI (enabled only when ConTask is selected) AND in the .ini file.

Ad 2.: I think it is a great idea to handle textures separately for all conditions. Otherwise, it would be a bottleneck in the future when user may want to use more images with higher resolution. I have overlooked it, because I rarely use PTB.

**Comment by lucp88** [comment]
Hi,

Changes:

- I cleaned and reorganized the stim folder: now only 5 example images with 10 instances each, stimnames are in a mat file which is read during ptb preperation similar to the int condition
- I added the TaskFolder entry in the GUI and in the .ini files
- I implemented the corresponding changes in OpenNFT.py 
- I changed the tex as discussed and seperated them from P struct. Did this for the other relevant protocol conditions as well. 
- After all the changes I tested the other conditions with the demo data as well

in nfbCalc 
- for int fb I changed minimum dispValue to 1 otherwise in case of 0 in displayfeedback indexing the corresponding smiley wont work

Please let me know if more changes need to be implemented or if things should be corrected/optimized

Lucas

**Comment by tiborauer** [comment]
@lucp88, thank you for the quick implementation!
I have also tested the PR and it is working as expected apart from a few smaller issues:
- https://github.com/OpenNFT/OpenNFT/blob/4902f507b53b505e680a57a676d93ac7b90ed381/OpenNFT.py#L201-L213 I have noticed that you open PTB helper with desktop. I do not think it is necessary. Actually, I have just tested with even the Main Helper with -nodektop so I suggest to change both accordingly.
- https://github.com/OpenNFT/OpenNFT/blob/4902f507b53b505e680a57a676d93ac7b90ed381/ini/NF_PSC_int_155.ini#L8 I have noticed a bug in the example ini, which is unrelated to this PR but should be corrected. The filename should be "001_000007_000001.dcm"
- https://github.com/OpenNFT/OpenNFT/blob/4902f507b53b505e680a57a676d93ac7b90ed381/matlab/nfbDispl/ptbPreparation.m#L160 Here, you changed the code incorrectly, which causes the smiley to be too small. Correcting for `w_dispRect = round(P.Screen.rectSm(4)*1.5);` solves the issue.

Feel free, to change the codes yourself, but I am also happy to submit a PR to your branch to update your PR , if you want.

**Comment by lucp88** [comment]
@tiborauer great, thank you for checking and feedback!

Yes, the desktop mode was for debugging/testing, forgot to put it back

haha i was already wondering why the smiley was so tiny! 

i will quickly make the corrections. Thank you!

**Comment by tiborauer** [comment]
Perfect!
Do not we want to switch nodesktop mode for the Main Helper, too?

**Comment by ykoush** [comment]
This is to test in previous version and merge with master.

**Comment by lucp88** [comment]
@ykoush let me know if you want me to change back the image texture handling.

**Comment by ykoush** [comment]
`Tex` is Ok. I'd put TaskFolder under Settings folder, for project-specific Settings, I can do it when updating Demo data.
I'd simplify this 
https://github.com/OpenNFT/OpenNFT/blob/fb97f674715acc000f612ddeda3238d4e204729a/matlab/mainLoopEntry.m#L24
but this is something for @da0c to double-check for time cross-referencing with `ptbTask.m`:
`% Get alternative experiment onset time stamp (in addition to recordEvent).
% Note, task process is uncoupled from data input.
if indVol == double(P.nrSkipVol)+1
    P.expOns = GetSecs; 
    fprintf('\n\n=============')
    fprintf('\nWe are live!')
    fprintf('\n=============\n\n')
end`

Otherwise, I checked and run through the changes except checking button clicks - I guess they are working as intended. So seems all ok. Could you please make these cahnges on top of a new OpenNFT version. This would take much less time than resolving data folders and other conflicts because we went to package? This also makes sense to follow the new updates, there will be quite a few, e.g. we are improving the gui viewer now.

**Pull request merged**
