### PR TITLE
Plugin

### PR DESCRIPTION
**Pull request by tiborauer**
**Major**:
This PR implements a plugin engine which allows addig plugins to OpenNFT. It also contains an example plugin.

**Minor**:
- Unthresholded statistical map (mainLoopData.tn) is not masked with the implicit brainmask
- Save code in refractored to allow premature termination without error

### CODE REVIEW

**Comment by espdev** [comment]
@tiborauer great work!

Currently, we are working on a new release in [RTQA_Patch_1](https://github.com/OpenNFT/OpenNFT/tree/RTQA_Patch_1) branch. 

Could you take a look at our changes? How difficult will it be to synchronize/merge our and your work?

**Comment by tiborauer** [comment]
I have already looked at your code and even adopted some changes (e.g. regarding the ui file management; see commit 783b525e85c16b1ea7c61275f29ebef6d74d8613).

However, I am not sure what you propose: 
1. Do you want to merge RTQA_Patch_1 into my PR (and/or also considering my other PRs) or the other way around?
2. Do you want to turn RTQA into a plugin?

N.B.: Merging this PR with the other two (esp. #50), may not go without conflict. I have already resolved it in my repo and [my master branch](https://github.com/tiborauer/OpenNFT/tree/master) already contains all of the three PRs. Would you prefer a single PR from my master instead of the three? Do you want to merge RTQA_Patch_1 with this PR or with the combined one?

**Comment by espdev** [comment]
I think we could make a release from RTQA_Patch_1 and merge all PRs after. We will have to resolve conflicts in any case.

**Comment by tiborauer** [comment]
Hi, This PR has been updated according to the latest improvement (rtQA+).

**Comment by tiborauer** [comment]
These conflicts are resolved in my master, so I should probably submit PR from my master (after #51)

**Comment by espdev** [comment]
@tiborauer could you enable "allow edits from maintainers" checkbox for the PR? @TheAmid wants to add a slight contributing to this PR.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by tiborauer** [comment]
If we are about to process this PR, I may need to resubmit a new one from my master, which resolved (some of) the conflicts.

**Comment by ykoush** [comment]
I think it could make sense, if @espdev doesn't have in mind something else. We are kind of working on all the remaining PRs at the same time now.

**Comment by tiborauer** [comment]
Done: #63 now includes #51 and #52.

**Comment by ykoush** [comment]
Closing, is a repetition of #63.

**Pull request closed without merging**
